
async function addSignatureHtml(business:any,entityType:string,id:string){try{const {getDb}=await import('@/src/db/database');const d=await getDb();const s=await d.getFirstAsync<any>('SELECT * FROM signatures WHERE entity_type=? AND entity_id=?',[entityType,id]);if(!s)return;const paths:string[]=JSON.parse(s.path_data||'[]');business.signatureHtml=`<div style="margin-top:24px"><b>Customer Signature</b><div style="margin-top:8px;border-bottom:1px solid #cfd3df;width:280px"><svg width="280" height="110" viewBox="0 0 330 250" preserveAspectRatio="xMinYMid meet">${paths.map(p=>`<path d="${p}" stroke="#17182e" stroke-width="2.4" fill="none" stroke-linecap="round"/>`).join('')}</svg></div><small>${s.signer_name||''}</small></div>`}catch{}}

async function addPhotoHtml(business:any,entityType:string,id:string){try{const {getDb}=await import('@/src/db/database');const d=await getDb();const rows=await d.getAllAsync<any>("SELECT * FROM attachments WHERE entity_type=? AND entity_id=? AND mime_type LIKE 'image/%' ORDER BY created_at LIMIT 4",[entityType,id]);const imgs=[];for(const a of rows){try{const b64=await FileSystem.readAsStringAsync(a.uri,{encoding:FileSystem.EncodingType.Base64});imgs.push(`<div style="width:48%;margin-bottom:10px"><img src="data:${a.mime_type};base64,${b64}" style="width:100%;max-height:180px;object-fit:cover;border-radius:8px"/><small>${a.name||''}</small></div>`)}catch{}}if(imgs.length)business.photoHtml=`<div style="margin-top:24px;page-break-inside:avoid"><b>Attached Photos</b><div style="display:flex;flex-wrap:wrap;gap:10px;margin-top:10px">${imgs.join('')}</div></div>`}catch{}}
import * as Print from 'expo-print';import * as Sharing from 'expo-sharing';import {documentWithItems,paymentsTotal,totals} from '@/src/db/repository';import {setting} from '@/src/db/database';import {invoiceHtml} from '@/src/templates/invoiceTemplates';import * as FileSystem from 'expo-file-system/legacy';
export async function makeInvoicePdf(id:string,share=true){const {doc,items}=await documentWithItems('invoice',id);const paid=await paymentsTotal(id);const t=totals(doc,items,paid);const currency=await setting('currency','ZAR');const business=JSON.parse(await setting('business_profile','{}')||'{}');if(business.logo_uri){try{const b64=await FileSystem.readAsStringAsync(business.logo_uri,{encoding:FileSystem.EncodingType.Base64});business.logoDataUri=`data:image/jpeg;base64,${b64}`}catch{}}await addSignatureHtml(business,'invoice',id);await addPhotoHtml(business,'invoice',id);const template=await setting('invoice_template','clean');const html=invoiceHtml(template,{doc,items,totals:t,business,currency});const out=await Print.printToFileAsync({html,base64:false});if(share&&await Sharing.isAvailableAsync())await Sharing.shareAsync(out.uri,{mimeType:'application/pdf',dialogTitle:`Share ${doc.number}`});return out.uri}

export async function makeEstimatePdf(id:string,share=true){const {doc,items}=await documentWithItems('estimate',id);const t=totals(doc,items,0);const currency=await setting('currency','ZAR');const business=JSON.parse(await setting('business_profile','{}')||'{}');if(business.logo_uri){try{const b64=await FileSystem.readAsStringAsync(business.logo_uri,{encoding:FileSystem.EncodingType.Base64});business.logoDataUri=`data:image/jpeg;base64,${b64}`}catch{}}await addSignatureHtml(business,'estimate',id);await addPhotoHtml(business,'estimate',id);const template=await setting('invoice_template','clean');const fake={...doc,due_date:doc.expiry_date,status:doc.status};const html=invoiceHtml(template,{doc:fake,items,totals:t,business,currency}).replace(/INVOICE/g,'ESTIMATE').replace(/Invoice/g,'Estimate');const out=await Print.printToFileAsync({html,base64:false});if(share&&await Sharing.isAvailableAsync())await Sharing.shareAsync(out.uri,{mimeType:'application/pdf',dialogTitle:`Share ${doc.number}`});return out.uri}
export async function printInvoicePdf(id:string){const uri=await makeInvoicePdf(id,false);await Print.printAsync({uri});}
export async function printEstimatePdf(id:string){const uri=await makeEstimatePdf(id,false);await Print.printAsync({uri});}
