import React,{useRef,useState} from 'react';import {Dimensions,FlatList,Image,Pressable,StyleSheet,Text,View} from 'react-native';import {router} from 'expo-router';import {SafeAreaView} from 'react-native-safe-area-context';import {Ionicons} from '@expo/vector-icons';import {useTheme} from '@/src/context/ThemeContext';
const W=Dimensions.get('window').width;
const slides=[
{title:'Run Your Business.\nNot Your Software.',body:'Professional estimates, invoices, jobs, clients and payments in one simple contractor app.',icon:'briefcase-outline',tag:'Always Free · No subscriptions'},
{title:'Free Means Free.',body:'Unlimited estimates. Unlimited invoices. Unlimited clients. Reports and backups included. No premium feature locks.',icon:'infinite-outline',tag:'Everything you need. Nothing held back.'},
{title:'Your Business.\nYour Data.',body:'Your business records stay on your device. No Unifill account. Export a complete backup anytime and restore it on another Android phone.',icon:'shield-checkmark-outline',tag:'Local-first by design'},
{title:'No Signal?\nKeep Working.',body:'Create estimates, invoices, clients, jobs, PDFs and reports without an internet connection.',icon:'cloud-offline-outline',tag:'Offline first'},
{title:'Ads Keep Unifill Free.',body:'Occasional, non-intrusive ads support development so every core business feature can stay free. Ads never interrupt important work.',icon:'heart-outline',tag:'Thanks for supporting a free tool'}];
export default function Onboarding(){const {theme}=useTheme();const ref=useRef<FlatList>(null);const [i,setI]=useState(0);const next=()=>{if(i===slides.length-1)router.replace('/setup');else ref.current?.scrollToIndex({index:i+1,animated:true})};return <SafeAreaView style={{flex:1,backgroundColor:theme.bg}}><View style={s.top}><Image source={require('@/assets/logo-horizontal.png')} style={s.logo} resizeMode="contain"/><Pressable onPress={()=>router.replace('/setup')}><Text style={{color:theme.muted,fontWeight:'700'}}>Skip</Text></Pressable></View><FlatList ref={ref} data={slides} horizontal pagingEnabled showsHorizontalScrollIndicator={false} keyExtractor={x=>x.title} onMomentumScrollEnd={e=>setI(Math.round(e.nativeEvent.contentOffset.x/W))} renderItem={({item})=><View style={[s.slide,{width:W}]}><View style={[s.ill,{backgroundColor:theme.surface,borderColor:theme.border}]}><Ionicons name={item.icon as any} size={78} color={theme.primary}/></View><Text style={[s.title,{color:theme.text}]}>{item.title}</Text><Text style={[s.body,{color:theme.muted}]}>{item.body}</Text><View style={[s.tag,{backgroundColor:theme.surfaceAlt}]}><Text style={{color:theme.primary,fontWeight:'800'}}>{item.tag}</Text></View></View>}/><View style={s.bottom}><View style={{flexDirection:'row',gap:7}}>{slides.map((_,n)=><View key={n} style={{width:n===i?24:7,height:7,borderRadius:10,backgroundColor:n===i?theme.primary:theme.border}}/>)}</View><Pressable onPress={next} style={[s.btn,{backgroundColor:theme.primary}]}><Text style={{color:'white',fontWeight:'900'}}>{i===slides.length-1?'Set Up My Business':'Continue'}</Text><Ionicons name="arrow-forward" color="white" size={18}/></Pressable><Text style={{color:theme.muted,fontSize:12}}>No account needed.</Text></View></SafeAreaView>}
const s=StyleSheet.create({top:{height:70,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{width:145,height:52},slide:{paddingHorizontal:28,alignItems:'center',justifyContent:'center',gap:18},ill:{width:160,height:160,borderWidth:1,borderRadius:40,alignItems:'center',justifyContent:'center'},title:{fontSize:33,fontWeight:'900',textAlign:'center',letterSpacing:-1},body:{fontSize:16,lineHeight:24,textAlign:'center',maxWidth:330},tag:{paddingHorizontal:16,paddingVertical:10,borderRadius:999},bottom:{padding:22,alignItems:'center',gap:16},btn:{width:'100%',height:52,borderRadius:16,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8}})
