import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Pressable,ScrollView,Text,View} from 'react-native';
import {router} from 'expo-router';import {Ionicons} from '@expo/vector-icons';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Button,Card,Field,Muted} from './UI';import {Header} from './Header';
import {documentWithItems,list,saveDocument,totals} from '@/src/db/repository';
import {dateISO,minorFromInput,money,uuid} from '@/src/lib/format';import {setting} from '@/src/db/database';import {useTheme} from '@/src/context/ThemeContext';import {maybeShowInterstitial} from '@/src/services/ads';

export function DocumentEditor({kind,id}:{kind:'estimate'|'invoice';id?:string}){
 const {theme}=useTheme();const [clients,setClients]=useState<any[]>([]),[jobs,setJobs]=useState<any[]>([]),[saved,setSaved]=useState<any[]>([]),[currency,setCurrency]=useState('ZAR');
 const [v,setV]=useState<any>({issue_date:dateISO(),status:'Draft',tax_rate:15,discount_minor:0,notes:'',terms:'',due_date:dateISO(new Date(Date.now()+14*86400000)),expiry_date:dateISO(new Date(Date.now()+14*86400000)),payment_instructions:''});
 const [items,setItems]=useState<any[]>([{id:uuid(),description:'',detail:'',quantity:1,unit_price_minor:0,taxable:1}]);
 useEffect(()=>{(async()=>{setClients(await list('clients','archived=0'));setJobs(await list('jobs','archived=0'));setSaved(await list('saved_items','archived=0'));setCurrency(await setting('currency','ZAR'));const tax=Number(await setting('tax_rate','15'));const paymentInstructions=await setting('payment_instructions','');const defaultTerms=await setting('default_terms','');setV((o:any)=>({...o,tax_rate:tax,payment_instructions:paymentInstructions,terms:defaultTerms}));if(id){const r=await documentWithItems(kind,id);if(r.doc)setV(r.doc);if(r.items?.length)setItems(r.items)}})()},[id,kind]);
 const t=useMemo(()=>totals(v,items,0),[v,items]);const f=(k:string)=>(x:string)=>setV((o:any)=>({...o,[k]:x}));
 const updateItem=(idx:number,k:string,val:any)=>setItems(xs=>xs.map((x,i)=>i===idx?{...x,[k]:val}:x));
 const save=async()=>{if(!v.client_id)return Alert.alert('Choose a client','An estimate or invoice needs a client.');if(!items.some(x=>x.description.trim()))return Alert.alert('Add at least one line item');const clean=items.filter(x=>x.description.trim());const newId=await saveDocument(kind,v,clean);maybeShowInterstitial().catch(()=>{});router.replace(`/${kind}?id=${newId}` as any)};
 return <SafeAreaView style={{flex:1,backgroundColor:theme.bg}}><Header title={`${id?'Edit':'New'} ${kind==='invoice'?'Invoice':'Estimate'}`} onBack={()=>router.back()}/><ScrollView contentContainerStyle={{padding:18,gap:14,paddingBottom:40}} keyboardShouldPersistTaps="handled">
 <Card><Muted>Client</Muted><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,marginTop:10}}>{clients.map(c=><Pressable key={c.id} onPress={()=>setV((o:any)=>({...o,client_id:c.id}))} style={{padding:10,borderRadius:12,backgroundColor:v.client_id===c.id?theme.primary:theme.surfaceAlt}}><Text style={{color:v.client_id===c.id?'white':theme.text,fontWeight:'800'}}>{c.company||c.name}</Text></Pressable>)}<Pressable onPress={()=>router.push('/client-edit')} style={{padding:10,borderRadius:12,backgroundColor:theme.surfaceAlt}}><Text style={{color:theme.primary,fontWeight:'900'}}>+ New client</Text></Pressable></ScrollView></Card>
 <Card><Muted>Job (optional)</Muted><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,marginTop:10}}><Pressable onPress={()=>setV((o:any)=>({...o,job_id:null}))} style={{padding:10,borderRadius:12,backgroundColor:!v.job_id?theme.primary:theme.surfaceAlt}}><Text style={{color:!v.job_id?'white':theme.text,fontWeight:'800'}}>None</Text></Pressable>{jobs.filter(j=>!v.client_id||j.client_id===v.client_id).map(j=><Pressable key={j.id} onPress={()=>setV((o:any)=>({...o,job_id:j.id}))} style={{padding:10,borderRadius:12,backgroundColor:v.job_id===j.id?theme.primary:theme.surfaceAlt}}><Text style={{color:v.job_id===j.id?'white':theme.text,fontWeight:'800'}}>{j.name}</Text></Pressable>)}</ScrollView></Card>
 <Card><Muted>Saved items / price book</Muted><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,marginTop:10}}>{saved.length?saved.map(si=><Pressable key={si.id} onPress={()=>setItems(xs=>[...xs,{id:uuid(),description:si.name,detail:si.description||'',quantity:1,unit_price_minor:si.selling_price_minor||0,taxable:si.taxable===0?0:1}])} style={{padding:10,borderRadius:12,backgroundColor:theme.surfaceAlt}}><Text style={{color:theme.text,fontWeight:'800'}}>{si.name}</Text></Pressable>):<Text style={{color:theme.muted}}>No saved items yet.</Text>}</ScrollView></Card>
 <View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Field label="Issue date" value={v.issue_date||''} onChangeText={f('issue_date')}/></View><View style={{flex:1}}><Field label={kind==='invoice'?'Due date':'Expiry date'} value={(kind==='invoice'?v.due_date:v.expiry_date)||''} onChangeText={f(kind==='invoice'?'due_date':'expiry_date')}/></View></View>
 <Card><Muted>Status</Muted><View style={{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:10}}>{(kind==='invoice'?['Draft','Sent','Partially Paid','Paid','Void']:['Draft','Sent','Viewed','Approved','Rejected','Expired','Converted']).map(st=><Pressable key={st} onPress={()=>setV((o:any)=>({...o,status:st}))} style={{paddingHorizontal:10,paddingVertical:8,borderRadius:999,backgroundColor:v.status===st?theme.primary:theme.surfaceAlt}}><Text style={{color:v.status===st?'white':theme.text,fontWeight:'800'}}>{st}</Text></Pressable>)}</View></Card>
 <Card>
 <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}>
   <Text style={{color:theme.text,fontSize:17,fontWeight:'900'}}>Line items</Text>
   <Pressable onPress={()=>setItems(xs=>[...xs,{id:uuid(),description:'',detail:'',quantity:1,unit_price_minor:0,taxable:1}])}><Text style={{color:theme.primary,fontWeight:'900'}}>+ Add item</Text></Pressable>
 </View>
 {items.map((x,idx)=><View key={x.id||idx} style={{gap:9,paddingTop:14,marginTop:10,borderTopWidth:idx?1:0,borderTopColor:theme.border}}>
   <View style={{flexDirection:'row',gap:8,alignItems:'flex-end'}}>
     <View style={{flex:1}}><Field label={`Item ${idx+1}`} value={x.description||''} onChangeText={z=>updateItem(idx,'description',z)} placeholder="Labour, materials, service…"/></View>
     {items.length>1&&<Pressable onPress={()=>setItems(xs=>xs.filter((_,i)=>i!==idx))} style={{height:48,width:42,alignItems:'center',justifyContent:'center'}}><Ionicons name="trash-outline" color={theme.danger} size={20}/></Pressable>}
   </View>
   <Field label="Description / detail" value={x.detail||''} onChangeText={z=>updateItem(idx,'detail',z)}/>
   <View style={{flexDirection:'row',gap:8}}>
     <View style={{flex:1}}><Field label="Qty" value={String(x.quantity??1)} onChangeText={z=>updateItem(idx,'quantity',Number(z)||0)} keyboardType="decimal-pad"/></View>
     <View style={{flex:2}}><Field label={`Unit price (${currency})`} value={(Number(x.unit_price_minor||0)/100).toFixed(2)} onChangeText={z=>updateItem(idx,'unit_price_minor',minorFromInput(z))} keyboardType="decimal-pad"/></View>
   </View>
   <Pressable onPress={()=>updateItem(idx,'taxable',x.taxable===0?1:0)} style={{alignSelf:'flex-start',paddingHorizontal:10,paddingVertical:7,borderRadius:999,backgroundColor:(x.taxable===0?theme.surfaceAlt:theme.success+'18')}}><Text style={{color:x.taxable===0?theme.muted:theme.success,fontWeight:'800'}}>{x.taxable===0?'Non-taxable':'Taxable'}</Text></Pressable>
 </View>)}
 </Card>
 <View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Field label="Discount" value={(Number(v.discount_minor||0)/100).toFixed(2)} onChangeText={z=>setV((o:any)=>({...o,discount_minor:minorFromInput(z)}))} keyboardType="decimal-pad"/></View><View style={{flex:1}}><Field label="Tax %" value={String(v.tax_rate??0)} onChangeText={z=>setV((o:any)=>({...o,tax_rate:Number(z)||0}))} keyboardType="decimal-pad"/></View></View>
 <Card><View style={{gap:8}}><Row label="Subtotal" value={money(t.subtotal,currency)} theme={theme}/><Row label="Discount" value={`-${money(t.discount,currency)}`} theme={theme}/><Row label={`Tax (${v.tax_rate||0}%)`} value={money(t.tax,currency)} theme={theme}/><View style={{height:1,backgroundColor:theme.border}}/><Row label="Total" value={money(t.total,currency)} theme={theme} bold/></View></Card>
 <Field label="Notes" value={v.notes||''} onChangeText={f('notes')} multiline/><Field label="Terms" value={v.terms||''} onChangeText={f('terms')} multiline/>{kind==='invoice'&&<Field label="Payment instructions" value={v.payment_instructions||''} onChangeText={f('payment_instructions')} multiline/>}<Button title={`Save ${kind==='invoice'?'Invoice':'Estimate'}`} onPress={save}/></ScrollView></SafeAreaView>
}
function Row({label,value,theme,bold=false}:{label:string;value:string;theme:any;bold?:boolean}){return <View style={{flexDirection:'row',justifyContent:'space-between'}}><Text style={{color:bold?theme.text:theme.muted,fontWeight:bold?'900':'600'}}>{label}</Text><Text style={{color:theme.text,fontWeight:bold?'900':'800'}}>{value}</Text></View>}
